[Song]
;
name = Modern Day Cowboy
artist = Tesla
album = Mechanical Resonance
genre = Classic Rock
year = 1986
song_length = 315999
diff_band = 3
diff_guitar = 3
diff_bass = 1
diff_drums = 3
diff_keys = -1
diff_guitarghl = -1
diff_bassghl = -1
preview_start_time = -1
frets = <color=orange>Neversoft</color>
charter=<color=orange>Neversoft</color>
icon = ghwor
album_track = 16000
playlist_track = 48
delay = 0
loading_phrase = Mechanical Resonance is the debut album by the American rock band Tesla. It was released in 1986. The album was certified platinum by RIAA on October 5, 1989.
