[Song]
;
name = Burnin' for You
artist = Blue Oyster Cult
album = Fire of Unknown Origin
genre = Classic Rock
year = 1993
song_length = 274533
diff_band = 2
diff_guitar = 2
diff_bass = 1
diff_drums = 1
diff_keys = -1
diff_guitarghl = -1
diff_bassghl = -1
preview_start_time = -1
frets = <color=orange>Neversoft</color>
charter=<color=orange>Neversoft</color>
icon = ghwor
album_track = 16000
playlist_track = 12
delay = 0
loading_phrase = This song was Blue Oyster Cult's first major radio hit since 1976's "(Don't Fear) The Reaper."
