[Song]
;
name = Cherry Bomb
artist = The Runaways
album = The Runaways
genre = Rock
year = 1976
song_length = 163533
diff_band = 2
diff_guitar = 2
diff_bass = 1
diff_drums = 2
diff_keys = -1
diff_guitarghl = -1
diff_bassghl = -1
preview_start_time = -1
frets = <color=orange>Neversoft</color>
charter=<color=orange>Neversoft</color>
icon = ghwor
album_track = 16000
playlist_track = 16
delay = 0
loading_phrase = Joan Jett became the biggest star to come out of The Runaways, and her story was the focus of their 2010 movie, where she was portrayed by the fetching Kristen Stewart.
