[Song]
;
name = Slow Hands
artist = Interpol
album = Antics
genre = Alternative
year = 2004
song_length = 192199
count = 1
diff_band = 2
diff_guitar = 2
diff_bass = 2
diff_drums = 2
diff_keys = -1
diff_guitarghl = -1
diff_bassghl = -1
preview_start_time = -1
frets = <color=orange>Neversoft</color>
charter=<color=orange>Neversoft</color>
icon = ghwor
playlist_track = 69
loading_phrase = This is a song about the painful and apathetic feelings of love and loss.
