[Song]
;
name = Fascination Street
artist = The Cure
album = Disintegration
genre = Alternative
year = 1989
song_length = 314333
count = 1
diff_band = 2
diff_guitar = 1
diff_bass = 1
diff_drums = 3
diff_keys = -1
diff_guitarghl = -1
diff_bassghl = -1
preview_start_time = -1
frets = <color=orange>Neversoft</color>
charter=<color=orange>Neversoft</color>
icon = ghwor
playlist_track = 22
loading_phrase = Even though this was and still is a fan favorite, it was only released as a single in the United States.
