[Song]
;
name = Dancing Through Sunday
artist = AFI
album = Sing the Sorrow
genre = Rock
year = 2003
song_length = 150799
count = 2
diff_band = 3
diff_guitar = 3
diff_bass = 2
diff_drums = 4
diff_keys = -1
diff_guitarghl = -1
diff_bassghl = -1
preview_start_time = -1
frets = <color=orange>Neversoft</color>
charter=<color=orange>Neversoft</color>
icon = ghwor
playlist_track = 20
loading_phrase = The band enjoyed its first major commercial success 12 years after it formed, in 2003, with Sing the Sorrow reaching number five on the Billboard 200, and remaining on the chart for 51 weeks.
