from typing import NamedTuple, Optional, Dict

class SongMeta(NamedTuple):
    """Contains difficulty information, Use None for unsupported intsruments"""

    group: str
    source: str
    guitar5F: Optional[int]
    bass5F: Optional[int]
    drums: Optional[int]
    drumsElite: Optional[int]
    keys5F: Optional[int]
    keysPro: Optional[int]
    vocals: Optional[int]
    harmony2: Optional[int]
    harmony3: Optional[int]
    rhythm5F: Optional[int]

Songs: Dict[str, SongMeta] = {
    "106": SongMeta("YARG Official Setlist", "yarg", 5, 4, 4, 4, None, None, 2, 2, 2, None),
    "1nput This 2 Y0ur Spine": SongMeta("YARG Official Setlist", "yarg", 6, 4, 6, 6, 6, 6, 0, None, None, None),
    "322": SongMeta("YARG Official Setlist", "yarg", 4, 4, 5, None, 3, 3, 0, None, None, None),
    "A Visitant (feat. Victor Borba)": SongMeta("YARG Official Setlist", "yarg", 3, 1, 5, None, 6, 6, 4, 4, None, None),
    "About the Author": SongMeta("YARG Official Setlist", "yarg", 3, 2, 2, None, 1, 1, 5, 5, 5, None),
    "The Afterparty": SongMeta("YARG Official Setlist", "yarg", 3, 1, 2, None, 2, 3, 3, 3, 3, None),
    "Al Gore Rhythm": SongMeta("YARG Official Setlist", "yarg", 5, 4, 5, None, None, None, 5, 5, 5, None),
    "Alibi": SongMeta("YARG Official Setlist", "yarg", 3, 3, 6, None, 0, 0, 4, 4, 4, None),
    "All of a Sudden": SongMeta("YARG Official Setlist", "yarg", 3, 3, 4, None, 2, 3, 1, 1, None, None),
    "Allure": SongMeta("YARG Official Setlist", "yarg", 5, 5, 6, None, 0, 0, 2, 2, 2, None),
    "Avatar the Last Cakebender": SongMeta("YARG Official Setlist", "yarg", 4, 3, 5, None, 4, 4, 4, 4, 4, None),
    "Avatara": SongMeta("YARG Official Setlist", "yarg", 2, 2, 4, 4, 2, 2, 0, 0, None, None),
    "Bathe in Blood": SongMeta("YARG Official Setlist", "yarg", 6, 2, 6, None, None, None, 0, None, None, None),
    "Bedroom Community": SongMeta("YARG Official Setlist", "yarg", 3, 3, 3, 3, 5, 5, 3, 3, 3, None),
    "Beverly": SongMeta("YARG Official Setlist", "yarg", 2, 2, 2, None, None, None, 2, 2, 2, None),
    "Blue (feat. Miori Celesta)": SongMeta("YARG Official Setlist", "yarg", 3, 5, 4, None, 5, 5, 5, 5, 5, None),
    "Boom Slayer (feat. Scott Foster Harris)": SongMeta("YARG Official Setlist", "yarg", 3, 3, 4, None, 2, 2, 3, 3, None, None),
    "Bottleneck": SongMeta("YARG Official Setlist", "yarg", 5, 5, 5, None, None, None, 3, 3, None, None),
    "Buds": SongMeta("YARG Official Setlist", "yarg", 2, 1, 2, None, None, None, 2, 2, 2, None),
    "Butterflies": SongMeta("YARG Official Setlist", "yarg", 3, 3, 4, 4, None, None, 1, 1, 1, None),
    "Choked Up": SongMeta("YARG Official Setlist", "yarg", 3, 1, 2, 2, 3, 4, 4, 4, 4, None),
    "Circles": SongMeta("YARG Official Setlist", "yarg", 3, 3, 3, None, 0, 0, 3, 3, 3, None),
    "Cowboy Tanaka": SongMeta("YARG Official Setlist", "yarg", 4, 3, 5, None, 5, 5, 4, 4, 4, None),
    "Cruisin'": SongMeta("YARG Official Setlist", "yarg", 5, 3, 4, None, 3, 3, None, None, None, None),
    "Discipline": SongMeta("YARG Official Setlist", "yarg", 3, 2, 2, 2, 2, 2, 3, 3, 3, None),
    "Do": SongMeta("YARG Official Setlist", "yarg", 3, 4, 5, None, 4, 4, 6, 6, None, None),
    "Don't Look!": SongMeta("YARG Official Setlist", "yarg", 2, 3, 4, None, 6, 6, 1, 1, 1, None),
    "Don't Spook the Owl": SongMeta("YARG Official Setlist", "yarg", 3, 3, 4, None, None, None, 4, 4, 4, None),
    "Dreamweaver": SongMeta("YARG Official Setlist", "yarg", 3, 3, 4, 4, None, None, 0, 0, 0, None),
    "Duvet Thief": SongMeta("YARG Official Setlist", "yarg", 2, 2, 4, None, 1, 2, 3, 3, 3, None),
    "Eleven": SongMeta("YARG Official Setlist", "yarg", 2, 2, 3, None, 0, 0, 2, 2, 2, None),
    "Emperor Rising": SongMeta("YARG Official Setlist", "yarg", 5, 5, 6, None, None, None, 4, 4, 4, None),
    "Empires": SongMeta("YARG Official Setlist", "yarg", 2, 1, 4, None, 4, 4, 4, 4, 4, None),
    "Everybody Do the Flop": SongMeta("YARG Official Setlist", "yarg", 4, 3, 5, None, 4, 4, 5, 5, 5, None),
    "Exeter": SongMeta("YARG Official Setlist", "yarg", 3, 4, 4, None, 0, 0, 2, 2, 2, None),
    "Fine": SongMeta("YARG Official Setlist", "yarg", 4, 2, 4, 4, 2, 2, 4, 4, 4, None),
    "Flight of the Bumblebee": SongMeta("YARG Official Setlist", "yarg", 6, 3, 6, None, None, None, None, None, None, None),
    "Formless Collective": SongMeta("YARG Official Setlist", "yarg", 6, 5, 8, None, None, None, 0, 0, 0, None),
    "Frank Scored a Video Game": SongMeta("YARG Official Setlist", "yarg", 6, 5, 5, None, None, None, None, None, None, None),
    "Front Row Seats (To Watching Your World Burn)": SongMeta("YARG Official Setlist", "yarg", 2, 2, 5, None, 1, 1, 3, 3, 3, None),
    "The Game": SongMeta("YARG Official Setlist", "yarg", 4, 2, 4, 4, 2, 2, 3, 3, 3, None),
    "God Only Knows (feat. Kasane Teto)": SongMeta("YARG Official Setlist", "yarg", 5, 5, 5, None, 4, 4, 3, 3, 3, None),
    "Guess I'll Never Know": SongMeta("YARG Official Setlist", "yarg", 1, 0, 3, None, 0, 0, 2, 2, 2, None),
    "Half Measures": SongMeta("YARG Official Setlist", "yarg", 0, 0, 1, None, 0, 1, 6, 6, 6, None),
    "I Don't Wanna Talk": SongMeta("YARG Official Setlist", "yarg", 3, 3, 3, None, 2, 2, 2, 2, 2, None),
    "I Wish That I Could Fall (feat. GUMI)": SongMeta("YARG Official Setlist", "yarg", 3, 5, 1, None, 5, 5, 5, 5, 5, None),
    "I'm a Bug": SongMeta("YARG Official Setlist", "yarg", 1, 1, 3, None, 5, 5, 2, 2, 2, None),
    "Igowallah": SongMeta("YARG Official Setlist", "yarg", 0, 2, 5, None, 0, 0, 4, 4, 4, None),
    "In My Head": SongMeta("YARG Official Setlist", "yarg", 1, 1, 2, None, None, None, 2, 2, 2, None),
    "Is This What You Wanted": SongMeta("YARG Official Setlist", "yarg", 4, 1, 2, None, 2, 2, 5, 5, 5, None),
    "It Kills Me": SongMeta("YARG Official Setlist", "yarg", 2, 2, 4, None, 1, 2, 3, 3, 3, None),
    "Jenny B": SongMeta("YARG Official Setlist", "yarg", 7, 4, 2, 2, None, None, 5, None, None, None),
    "John, Take Me with You": SongMeta("YARG Official Setlist", "yarg", 2, 2, 2, None, None, None, 2, 2, 2, None),
    "Join the Club": SongMeta("YARG Official Setlist", "yarg", 3, 2, 2, None, 3, 3, 3, 3, 3, None),
    "Languish": SongMeta("YARG Official Setlist", "yarg", 4, 3, 5, 5, 2, 2, 0, 0, 0, None),
    "Long in the Tooth": SongMeta("YARG Official Setlist", "yarg", 5, 3, 5, 5, 3, 3, 2, 2, 2, None),
    "Luminaire": SongMeta("YARG Official Setlist", "yarg", 3, 3, 7, None, 5, 5, None, None, None, None),
    "Marlboro Mountain": SongMeta("YARG Official Setlist", "yarg", 3, 3, 3, None, 0, 0, 3, 3, 3, None),
    "The Masquerade": SongMeta("YARG Official Setlist", "yarg", 4, 4, 4, None, 5, 5, 2, 2, 2, None),
    "Mass Gap": SongMeta("YARG Official Setlist", "yarg", 6, 6, 6, None, 6, 7, None, None, None, None),
    "Moonlight Sonata 3rd Mvt (Big Band Version)": SongMeta("YARG Official Setlist", "yarg", 3, 5, 7, None, 6, 6, None, None, None, None),
    "Need 2": SongMeta("YARG Official Setlist", "yarg", 3, 0, 0, None, 2, 2, 1, 1, 1, None),
    "The New World Disorder": SongMeta("YARG Official Setlist", "yarg", 7, 7, 6, 6, None, None, 3, 3, 3, None),
    "No Nations": SongMeta("YARG Official Setlist", "yarg", 0, 1, 0, None, 0, 0, 1, 1, 1, None),
    "No Remedy": SongMeta("YARG Official Setlist", "yarg", 1, 1, 3, None, 3, 3, 2, 2, 2, None),
    "Nomu": SongMeta("YARG Official Setlist", "yarg", 3, 2, 3, None, None, None, 5, 5, 5, None),
    "Numb the Mind": SongMeta("YARG Official Setlist", "yarg", 1, 0, 2, None, 0, 0, 2, None, None, None),
    "Oh, Krissy Baby!": SongMeta("YARG Official Setlist", "yarg", 3, 2, 2, None, 3, 3, 4, 4, 4, None),
    "Oopsie Daisy": SongMeta("YARG Official Setlist", "yarg", 1, 3, 2, None, 2, 2, 3, 3, 3, None),
    "Over Again": SongMeta("YARG Official Setlist", "yarg", 2, 1, 2, None, 1, 1, 5, 5, 5, None),
    "Overdrive": SongMeta("YARG Official Setlist", "yarg", 3, 2, 3, None, None, None, 3, None, None, None),
    "Oxygen": SongMeta("YARG Official Setlist", "yarg", 2, 1, 2, None, 2, 2, 2, 2, 2, None),
    "Participation Trophy Wife": SongMeta("YARG Official Setlist", "yarg", 4, 3, 3, None, None, None, 3, 3, None, None),
    "Pixel Galaxy": SongMeta("YARG Official Setlist", "yarg", 6, 2, 4, None, 3, 3, None, None, None, None),
    "Pizza Rolls": SongMeta("YARG Official Setlist", "yarg", 5, 1, 2, 2, None, None, 2, 2, 2, None),
    "Plastic Boogie": SongMeta("YARG Official Setlist", "yarg", 3, 3, 1, None, 1, 1, 2, 2, 2, None),
    "Poser": SongMeta("YARG Official Setlist", "yarg", 4, 3, 3, None, None, None, 4, 4, 4, None),
    "Positively Clark Street": SongMeta("YARG Official Setlist", "yarg", 4, 2, 2, None, 2, 2, 4, 4, 4, None),
    "Queen of the Night": SongMeta("YARG Official Setlist", "yarg", 3, 4, 3, None, 3, 3, 4, 4, 4, None),
    "Runnin Man": SongMeta("YARG Official Setlist", "yarg", 3, 3, 5, 5, None, None, 0, 0, 0, None),
    "Sadness (feat. Sapphire Noel)": SongMeta("YARG Official Setlist", "yarg", 2, 2, 5, None, 2, 2, 2, 2, None, None),
    "Seasons (feat. Shiki Miyoshino)": SongMeta("YARG Official Setlist", "yarg", 2, 1, 0, None, 1, 2, 3, 3, None, None),
    "Show Ya": SongMeta("YARG Official Setlist", "yarg", 2, 0, 2, None, 2, 2, 3, 3, 3, None),
    "Smile for Me": SongMeta("YARG Official Setlist", "yarg", 4, 2, 4, None, None, None, 3, 3, 3, None),
    "Song of November": SongMeta("YARG Official Setlist", "yarg", 4, 4, 4, None, 1, 1, 3, 3, 3, None),
    "Spirit": SongMeta("YARG Official Setlist", "yarg", 2, 1, 1, None, 2, 2, 3, 3, 3, None),
    "Splinter": SongMeta("YARG Official Setlist", "yarg", 2, 0, 1, None, 2, 3, 3, 3, 3, None),
    "Stowaway Ants": SongMeta("YARG Official Setlist", "yarg", 3, 2, 4, None, 4, 4, 3, 3, 3, None),
    "Strangers Once Again (feat. Treb and Ofir Tabakov)": SongMeta("YARG Official Setlist", "yarg", 4, 3, 6, None, 4, 6, 5, 5, 5, None),
    "Sweet Victory": SongMeta("YARG Official Setlist", "yarg", 3, 1, 2, None, 3, 3, 3, 3, 3, None),
    "Synthespian": SongMeta("YARG Official Setlist", "yarg", 5, 5, 6, None, None, None, 2, 2, None, None),
    "They Call": SongMeta("YARG Official Setlist", "yarg", 4, 4, 4, None, None, None, 2, 2, 2, None),
    "Time": SongMeta("YARG Official Setlist", "yarg", 3, 2, 4, 4, 0, 0, 3, 3, 3, None),
    "To Let Go": SongMeta("YARG Official Setlist", "yarg", 3, 3, 4, None, 1, 1, 4, 4, 4, None),
    "Vehemence": SongMeta("YARG Official Setlist", "yarg", 6, 4, 6, None, None, None, None, None, None, None),
    "Voidwalker": SongMeta("YARG Official Setlist", "yarg", 4, 3, 5, None, 0, 0, 0, 0, 0, None),
    "We All Float Down Here": SongMeta("YARG Official Setlist", "yarg", 6, 4, 5, None, None, None, 2, 2, None, None),
    "Burn": SongMeta("Assorted Rock 1", "yargdlc", 1, 0, 1, None, None, None, 1, 1, 1, None),
    "Dunken Monday (Freeway Mix)": SongMeta("Assorted Rock 1", "yargdlc", 3, 2, 1, 2, None, None, 3, 3, 3, 3),
    "Middle of the City Road": SongMeta("Assorted Rock 1", "yargdlc", 3, 3, 2, 2, 1, 1, None, None, None, 1),
    "Moonlight": SongMeta("Assorted Rock 1", "yargdlc", 2, 0, None, None, 1, 1, 1, None, None, None),
    "Rock Thing": SongMeta("Assorted Rock 1", "yargdlc", 3, 1, 3, None, 4, 4, None, None, None, None),
    "Simplicity": SongMeta("Assorted Rock 1", "yargdlc", 1, 0, 1, None, 2, 2, None, None, None, None),
    "Turtleneck": SongMeta("Assorted Rock 1", "yargdlc", 3, 1, 3, None, 2, 2, None, None, None, None),
    "By the Seaside (feat. Kitsui Akira)": SongMeta("Assorted Electronic 1", "yargdlc", 3, 1, 6, None, 3, 3, 3, 3, None, None),
    "Feel Good": SongMeta("Assorted Electronic 1", "yargdlc", 2, 1, 1, None, 2, 3, 2, 2, None, None),
    "Ghost": SongMeta("Assorted Electronic 1", "yargdlc", 3, 1, 2, None, 2, 2, 4, 4, None, None),
    "Radioactive": SongMeta("Assorted Electronic 1", "yargdlc", 2, 6, 5, 5, 4, 5, 0, None, None, 2),
    "Rot for Clout (feat. Kasane Teto)": SongMeta("Assorted Electronic 1", "yargdlc", 3, 4, 4, None, 4, 5, 6, 6, None, 3),
    "Say It Back": SongMeta("Assorted Electronic 1", "yargdlc", 4, 2, 4, None, 4, 5, 5, 5, None, None),
    "Space and Time! (feat. Jelly Hoshiumi)": SongMeta("Assorted Electronic 1", "yargdlc", 7, 2, 0, None, 4, 5, 3, 3, 3, None),
    "Angel in Disguise (feat. Kitsui Akira)": SongMeta("SUMMERTIDE", "yargdlc", 2, 2, 2, None, 3, 3, 5, 5, None, None),
    "Cinnamon (feat. Miori Celesta and Yuuna Nini)": SongMeta("SUMMERTIDE", "yargdlc", 2, 1, 3, None, 2, 2, 6, 6, 6, None),
    "Embrace (feat. Kiyon)": SongMeta("SUMMERTIDE", "yargdlc", 5, 3, 2, None, 3, 3, 4, 4, 4, 4),
    "Heart of Glass (feat. Rachie)": SongMeta("SUMMERTIDE", "yargdlc", 2, 3, 4, None, 3, 3, 6, 6, None, None),
    "Hopeless Romantic (feat. JubyPhonic)": SongMeta("SUMMERTIDE", "yargdlc", 0, 0, 2, None, 2, 3, 3, 3, 3, None),
    "Love Me Not (feat. Tofie)": SongMeta("SUMMERTIDE", "yargdlc", 4, 0, 1, None, 2, 2, 4, 4, 4, None),
    "Magazines (feat. Nia Suzune)": SongMeta("SUMMERTIDE", "yargdlc", 3, 2, 2, None, 1, 3, 5, 5, 5, None),
    "One Step at a Time (feat. Miori Celesta)": SongMeta("SUMMERTIDE", "yargdlc", 3, 2, 3, None, 2, 2, 3, 3, 3, 6),
    "Rose (feat. Ember Amane)": SongMeta("SUMMERTIDE", "yargdlc", 2, 1, 1, None, 2, 2, 3, 3, 3, None),
    "Through the Night (feat. Yuuka Bear)": SongMeta("SUMMERTIDE", "yargdlc", 5, 4, 2, None, 2, 2, 4, 4, 4, 4),
    "Cars": SongMeta("WANDERKID", "yargdlc", 3, 1, None, None, None, None, 2, 2, 2, None),
    "Don't Fall Apart": SongMeta("WANDERKID", "yargdlc", 3, 2, 2, None, 0, 0, 2, 2, None, None),
    "Fake It Till You Make It": SongMeta("WANDERKID", "yargdlc", 1, 0, 1, 1, 0, 0, 1, None, None, None),
    "Holy Mountain": SongMeta("WANDERKID", "yargdlc", 3, 4, 4, None, 2, 2, 4, None, None, 4),
    "I Love You": SongMeta("WANDERKID", "yargdlc", 2, 2, 2, None, 1, 2, 2, 2, None, None),
    "I'm Probably a Ghost": SongMeta("WANDERKID", "yargdlc", 3, 2, 4, 4, 0, 0, 2, None, None, None),
    "Make Another Record": SongMeta("WANDERKID", "yargdlc", 3, 2, 4, None, 1, 1, 2, None, None, None),
    "Maybe": SongMeta("WANDERKID", "yargdlc", 1, 3, 4, None, 2, 2, 4, 4, 4, None),
    "Only with You": SongMeta("WANDERKID", "yargdlc", 1, 2, 1, 1, 1, 2, 3, 3, 3, None),
    "Wanderkid": SongMeta("WANDERKID", "yargdlc", 1, 3, 4, None, 0, 0, 4, 4, None, None),
    "Bridal Chorus": SongMeta("Classical Keys Pack 1", "yargdlc", None, 3, None, None, 3, 3, None, None, None, None),
    "Clair de Lune": SongMeta("Classical Keys Pack 1", "yargdlc", None, 2, None, None, 2, 2, None, None, None, None),
    "Entrance of the Gladiators": SongMeta("Classical Keys Pack 1", "yargdlc", None, 4, None, None, 4, 4, None, None, None, None),
    "Maple Leaf Rag": SongMeta("Classical Keys Pack 1", "yargdlc", None, 3, None, None, 5, 5, None, None, None, None),
    "Marche Funèbre": SongMeta("Classical Keys Pack 1", "yargdlc", None, 2, None, None, 2, 2, None, None, None, None),
    "Scherzo No. 1": SongMeta("Classical Keys Pack 1", "yargdlc", None, 5, None, None, 7, 7, None, None, None, None),
    "Frère Jacques": SongMeta("Children's Keys Pack 1", "yargdlc", None, 0, None, None, 1, 1, None, None, None, None),
    "Happy Birthday to You": SongMeta("Children's Keys Pack 1", "yargdlc", None, 0, None, None, 0, 0, None, None, None, None),
    "Mary Had a Little Lamb": SongMeta("Children's Keys Pack 1", "yargdlc", None, 0, None, None, 0, 0, None, None, None, None),
    "Rock-a-Bye Baby": SongMeta("Children's Keys Pack 1", "yargdlc", None, 1, None, None, 1, 1, None, None, None, None),
    "Row, Row, Row Your Boat": SongMeta("Children's Keys Pack 1", "yargdlc", None, 0, None, None, 1, 1, None, None, None, None),
    "Twinkle, Twinkle Little Star": SongMeta("Children's Keys Pack 1", "yargdlc", None, 0, None, None, 0, 0, None, None, None, None),
    "Dance of the Sugar Plum Fairy": SongMeta("Christmas Keys 1", "yargdlc", None, 4, None, None, 4, 4, None, None, None, None),
    "Deck the Halls": SongMeta("Christmas Keys 1", "yargdlc", None, 2, None, None, 3, 3, None, None, None, None),
    "Good King Wenceslas": SongMeta("Christmas Keys 1", "yargdlc", None, 0, None, None, 0, 0, None, None, None, None),
    "Jingle Bells": SongMeta("Christmas Keys 1", "yargdlc", None, 3, None, None, 2, 2, None, None, None, None),
    "Jolly Old Saint Nicholas": SongMeta("Christmas Keys 1", "yargdlc", None, 0, None, None, 1, 1, None, None, None, None),
    "Joy to the World": SongMeta("Christmas Keys 1", "yargdlc", None, 1, None, None, 2, 2, None, None, None, None),
    "Amelioration": SongMeta("YARN Pack 1", "yarn", 6, 4, 6, None, None, None, None, None, None, None),
    "Burn": SongMeta("YARN Pack 1", "yarn", 2, 1, None, None, None, None, None, None, None, 2),
    "Eviternal": SongMeta("YARN Pack 1", "yarn", 5, 4, 6, None, 4, 5, 5, 5, 5, None),
    "Fearfulness": SongMeta("YARN Pack 1", "yarn", 10, None, None, None, None, None, None, None, None, None),
    "How": SongMeta("YARN Pack 1", "yarn", 4, None, None, None, None, None, None, None, None, None),
    "I'm mindless :3": SongMeta("YARN Pack 1", "yarn", 8, None, None, None, None, None, None, None, None, None),
    "Reaper (2023 Remaster)": SongMeta("YARN Pack 1", "yarn", 6, 3, 6, None, None, None, None, None, None, None),
    "Second Wind": SongMeta("YARN Pack 1", "yarn", 3, 6, 6, 6, 3, 3, None, None, None, None),
    "Ways of Torment": SongMeta("YARN Pack 1", "yarn", 5, None, None, None, None, None, None, None, None, None),
    "Whispers (Rose Ver.)": SongMeta("YARN Pack 1", "yarn", 2, 1, 2, None, None, None, None, None, None, None),
    "Abomination": SongMeta("Mini-Wave 0", "yarn", 4, None, 6, None, None, None, 1, None, None, None),
    "Back To School Bitches (Kiraken-G Remix)": SongMeta("Mini-Wave 0", "yarn", 10, None, None, None, None, None, None, None, None, None),
    "Brain Implosion Energy Drink (feat. Kasane Teto and Eleanor Forte)": SongMeta("Mini-Wave 0", "yarn", 2, 1, 3, None, 1, 1, 4, 4, None, None),
    "Code 75": SongMeta("Mini-Wave 0", "yarn", 4, 2, 4, None, 3, 3, 4, 4, 4, None),
    "Dance Mr. Funnybones (LOOP)": SongMeta("Mini-Wave 0", "yarn", 1, 1, 2, None, None, None, None, None, None, 0),
    "Hard Licker": SongMeta("Mini-Wave 0", "yarn", 4, 4, 5, None, None, None, None, None, None, None),
    "help, the sillies are after me!1!!!1": SongMeta("Mini-Wave 0", "yarn", None, 3, 4, 4, 4, 4, None, None, None, None),
    "Nice Logo": SongMeta("Mini-Wave 0", "yarn", 2, 1, 2, None, 2, 2, 0, None, None, None),
    "opus_10": SongMeta("Mini-Wave 0", "yarn", None, 5, None, None, 6, 6, None, None, None, None),
    "Still Got It": SongMeta("Mini-Wave 0", "yarn", 2, 2, 2, None, None, None, None, None, None, None),
    "Wou Wou Wou": SongMeta("Mini-Wave 0", "yarn", 6, None, None, None, None, None, 0, None, None, None),
    "Control": SongMeta("Assorted Metal 1", "yargdlc", 3, 3, 2, None, 3, 3, 3, 3, 3, 3),
    "Full Body Plutonium": SongMeta("Assorted Metal 1", "yargdlc", 4, 3, 5, 5, None, None, 3, 3, None, 3),
    "Harbinger of Pestilence": SongMeta("Assorted Metal 1", "yargdlc", 6, 3, 6, 6, None, None, None, None, None, 4),
    "Hell": SongMeta("Assorted Metal 1", "yargdlc", 4, 2, 5, None, 0, 0, 3, 3, 3, 4),
    "Simple Folds": SongMeta("Assorted Metal 1", "yargdlc", 3, 3, 4, None, 3, 3, 4, 4, 4, 3),
    "Sleep Cycles": SongMeta("Assorted Metal 1", "yargdlc", 3, 3, 4, None, 2, 2, 1, 1, 1, 3),
    "The Mortal Plane": SongMeta("Assorted Metal 1", "yargdlc", 5, 3, 5, None, 5, 5, None, None, None, 4),
    "What You Really Want": SongMeta("Assorted Metal 1", "yargdlc", 5, 4, 3, None, 5, 5, 4, 4, 4, 5),
    "Chopsticks": SongMeta("Children's Keys Pack 2", "yargdlc", None, 1, None, None, 2, 2, None, None, None, None),
    "Hey Diddle Diddle": SongMeta("Children's Keys Pack 2", "yargdlc", None, 0, None, None, 0, 0, None, None, None, None),
    "Old MacDonald Had a Farm": SongMeta("Children's Keys Pack 2", "yargdlc", None, 0, None, None, 1, 1, None, None, None, None),
    "Over the River and Through the Woods": SongMeta("Children's Keys Pack 2", "yargdlc", None, 1, None, None, 1, 1, None, None, None, None),
    "Pop Goes the Weasel": SongMeta("Children's Keys Pack 2", "yargdlc", None, 1, None, None, 0, 0, None, None, None, None),
    "Three Blind Mice": SongMeta("Children's Keys Pack 2", "yargdlc", None, 0, None, None, 1, 1, None, None, None, None),
    "Funiculì, Funiculà": SongMeta("Classical Keys Pack 2", "yargdlc", None, 3, None, None, 3, 3, None, None, None, None),
    "Hungarian Rhapsody No. 2": SongMeta("Classical Keys Pack 2", "yargdlc", None, 6, None, None, 7, 7, None, None, None, None),
    "Minuet in G Major": SongMeta("Classical Keys Pack 2", "yargdlc", None, 1, None, None, 1, 1, None, None, None, None),
    "Piano Sonata No. 16, Mvt. I: Allegro": SongMeta("Classical Keys Pack 2", "yargdlc", None, 5, None, None, 5, 5, None, None, None, None),
    "The Well-Tempered Clavier Book 1 No. 1: Prelude and Fugue in C Major": SongMeta("Classical Keys Pack 2", "yargdlc", None, 0, None, None, 2, 2, None, None, None, None),
    "Twelfth Street Rag": SongMeta("Classical Keys Pack 2", "yargdlc", None, 3, None, None, 6, 6, None, None, None, None),
    "Below the Waves": SongMeta("FX4", "yarn", 4, 4, 5, None, None, None, None, None, None, None),
    "First Flight": SongMeta("FX4", "yarn", 5, 6, 6, None, None, None, None, None, None, None),
    "HBO Feature Presentation": SongMeta("FX4", "yarn", 2, 0, 2, None, None, None, None, None, None, None),
    "Incident Zero": SongMeta("FX4", "yarn", 4, 5, 6, None, None, None, None, None, None, None),
    "Journey into the Rift": SongMeta("FX4", "yarn", 5, 4, 7, None, None, None, None, None, None, None),
    "Reconstruct": SongMeta("FX4", "yarn", 5, 3, 3, None, None, None, None, None, None, None),
    "Singularity": SongMeta("FX4", "yarn", 5, 4, 6, None, None, None, None, None, None, None),
    "The Time Vampire": SongMeta("FX4", "yarn", 5, 4, 6, None, None, None, None, None, None, None),
    "Undone": SongMeta("FX4", "yarn", 4, 4, 5, None, None, None, None, None, None, None),
    "Weapon": SongMeta("FX4", "yarn", 4, 4, 6, None, None, None, None, None, None, None),
    "Abyss of Time": SongMeta("Abyss of Time", "yarn", 3, 2, 3, None, None, None, 3, 3, 3, None),
    "Aphrodite": SongMeta("Abyss of Time", "yarn", 4, 4, 5, None, None, None, 2, 2, None, None),
    "Bleed Your Hate Out": SongMeta("Abyss of Time", "yarn", 4, 4, 5, None, None, None, 3, 3, None, None),
    "Death Drive": SongMeta("Abyss of Time", "yarn", 2, 3, 4, None, None, None, 3, 3, 3, None),
    "Desert Rose": SongMeta("Abyss of Time", "yarn", 3, 2, 3, None, None, None, 2, 2, None, None),
    "Destroyer of Worlds": SongMeta("Abyss of Time", "yarn", 3, 3, 5, None, None, None, 1, 1, 1, None),
    "Impossible": SongMeta("Abyss of Time", "yarn", 4, 4, 4, None, None, None, 3, 3, None, None),
    "Inertia": SongMeta("Abyss of Time", "yarn", 2, 1, 2, None, None, None, 3, 3, None, None),
    "Mind Like a Minefield": SongMeta("Abyss of Time", "yarn", 3, 3, 4, None, None, None, 4, 4, 4, None),
    "Scorch the Earth": SongMeta("Abyss of Time", "yarn", 3, 3, 4, None, None, None, 4, None, None, None),
    "Summer Rain": SongMeta("Abyss of Time", "yarn", 3, 2, 3, None, None, None, 3, None, None, None),
    "Swallow": SongMeta("Abyss of Time", "yarn", 2, 2, 3, None, None, None, 2, 2, 2, None),
    "The Penalty": SongMeta("Abyss of Time", "yarn", 5, 4, 6, None, None, None, 3, 3, None, None),
    "Unclear Warfare": SongMeta("Abyss of Time", "yarn", 3, 2, 3, None, None, None, 4, 4, 4, None),
    "We've Seen Better Days": SongMeta("Abyss of Time", "yarn", 2, 1, 2, None, None, None, 3, 3, 3, None),
    "200": SongMeta("Plastic Death", "yarn", 1, 1, 4, None, None, None, None, None, None, None),
    "Abyss Angel": SongMeta("Plastic Death", "yarn", 2, 1, 4, None, None, None, None, None, None, None),
    "Coelacanth": SongMeta("Plastic Death", "yarn", 3, 2, 3, None, None, None, None, None, None, None),
    "Commatose": SongMeta("Plastic Death", "yarn", 6, 2, 4, None, None, None, None, None, None, None),
    "Cul-de-Sac": SongMeta("Plastic Death", "yarn", 3, 1, 3, None, None, None, None, None, None, None),
    "Guitar Song": SongMeta("Plastic Death", "yarn", 1, 1, 3, None, None, None, None, None, None, None),
    "Motions": SongMeta("Plastic Death", "yarn", 2, 1, 3, None, None, None, None, None, None, None),
    "Puppy": SongMeta("Plastic Death", "yarn", 2, 1, 3, None, None, None, None, None, None, None),
    "Rare Animal": SongMeta("Plastic Death", "yarn", 3, 2, 3, None, None, None, None, None, None, None),
    "Slip under the Door": SongMeta("Plastic Death", "yarn", 3, 1, 3, None, None, None, None, None, None, None),
    "The CIA": SongMeta("Plastic Death", "yarn", 5, 1, 5, None, None, None, None, None, None, None),
    "The Killer": SongMeta("Plastic Death", "yarn", 1, 1, 2, None, None, None, None, None, None, None),
    "Whalefall": SongMeta("Plastic Death", "yarn", 3, 1, 6, None, None, None, None, None, None, None),
    "Dance Like an Idiot": SongMeta("Assorted Rock 2", "yargdlc", 4, 3, 2, 2, 4, 4, 4, 4, 4, 3),
    "Let Me Dance (feat. Miori Celesta)": SongMeta("Assorted Rock 2", "yargdlc", 5, 2, 1, None, 2, 3, 2, 2, 2, None),
    "Like I Used to Be": SongMeta("Assorted Rock 2", "yargdlc", 2, 2, 3, None, None, None, 1, 1, 1, None),
    "North Carolina": SongMeta("Assorted Rock 2", "yargdlc", 2, 0, 1, None, None, None, 1, 1, None, None),
    "Safehouse": SongMeta("Assorted Rock 2", "yargdlc", 5, 4, 5, None, 6, 6, 5, 5, 5, 4),
    "Surf Song": SongMeta("Assorted Rock 2", "yargdlc", 5, 3, 5, None, None, None, 2, 2, None, None),
    "Until the Wind Blows Us Away (feat. Leucinjel)": SongMeta("Assorted Rock 2", "yargdlc", 4, 2, 2, None, 0, 1, 2, 2, None, None),
    "All These Darlings and Now Me": SongMeta("YARN Pack 2", "yarn", 5, None, None, None, None, None, None, None, None, None),
    "Alternative Ego": SongMeta("YARN Pack 2", "yarn", 8, 6, 8, None, None, None, None, None, None, None),
    "Apple Fritter": SongMeta("YARN Pack 2", "yarn", 2, 2, 3, None, None, None, None, None, None, None),
    "BIRDBRAIN (feat. OK Glass and Kasane Teto)": SongMeta("YARN Pack 2", "yarn", 3, 3, 4, None, None, None, 5, None, None, None),
    "Country": SongMeta("YARN Pack 2", "yarn", 4, 0, 1, None, 2, 3, 3, 3, 3, None),
    "Desolate Memory": SongMeta("YARN Pack 2", "yarn", 4, None, 5, None, None, None, None, None, None, None),
    "Glass Beach": SongMeta("YARN Pack 2", "yarn", 3, 2, 4, None, None, None, None, None, None, None),
    "Keep Your Guard Up": SongMeta("YARN Pack 2", "yarn", 4, 3, 5, None, 4, 4, None, None, None, None),
    "Machine Love (feat. Kasane Teto)": SongMeta("YARN Pack 2", "yarn", 3, 3, 3, None, None, None, 4, None, None, None),
    "Madtown": SongMeta("YARN Pack 2", "yarn", 0, 3, 2, 2, 1, 1, 1, 1, None, 0),
    "Stranded": SongMeta("YARN Pack 2", "yarn", 4, 2, 5, None, None, None, None, None, None, None),
    "Underground Popstars": SongMeta("YARN Pack 2", "yarn", 3, 2, 2, None, None, None, 2, None, None, None),
    "999,999 / 1,000,000": SongMeta("The Slip", "yargdlc", 3, 2, 3, 3, 2, 2, 4, 4, 4, 1),
    "Corona Radiata": SongMeta("The Slip", "yargdlc", 1, 0, 0, 0, 0, 1, None, None, None, 0),
    "Demon Seed": SongMeta("The Slip", "yargdlc", 2, 1, 4, 4, 2, 2, 3, 3, 3, 1),
    "Echoplex": SongMeta("The Slip", "yargdlc", 3, 2, 4, 4, 0, 0, 2, 2, 2, 2),
    "Head Down": SongMeta("The Slip", "yargdlc", 4, 1, 4, 4, 4, 3, 2, 2, None, 3),
    "Letting You": SongMeta("The Slip", "yargdlc", 4, 2, 6, 6, 1, 1, 2, 2, 2, 4),
    "Lights in the Sky": SongMeta("The Slip", "yargdlc", 0, 0, None, None, 0, 1, 2, None, None, None),
    "The Four of Us Are Dying": SongMeta("The Slip", "yargdlc", 2, 2, 3, 3, 2, 2, None, None, None, 3),
    "Alive (feat. Jeremy Fagan)": SongMeta("YARN Pack 3", "yarn", 4, 3, 5, None, None, 1, 3, 3, 3, 3),
    "BUTCHER VANITY (ft. Yi Xi)": SongMeta("YARN Pack 3", "yarn", 1, 4, 4, None, None, None, 6, 6, 6, None),
    "Cascade": SongMeta("YARN Pack 3", "yarn", 6, None, None, None, None, None, None, None, None, None),
    "Don't Touch My Plushies": SongMeta("YARN Pack 3", "yarn", 3, 3, 3, None, None, None, 3, None, None, None),
    "Guardian Angel": SongMeta("YARN Pack 3", "yarn", 5, None, None, None, None, None, None, None, None, None),
    "Kimi no Taion (feat. Eleanor Forte)": SongMeta("YARN Pack 3", "yarn", 3, 3, 2, None, None, None, 4, None, None, None),
    "n u l l s t a r _": SongMeta("YARN Pack 3", "yarn", 5, 0, None, None, 3, 5, None, None, None, None),
    "phleps": SongMeta("YARN Pack 3", "yarn", 2, 1, 0, None, 0, 1, 1, None, None, None),
    "Retry Now (feat. Hatsune Miku)": SongMeta("YARN Pack 3", "yarn", 5, None, None, None, None, None, 6, None, None, None),
    "Year fo the Toad (YOTT)": SongMeta("YARN Pack 3", "yarn", 3, 2, 5, None, None, None, 3, 3, 3, None),
    "Deep Geyser Tunez": SongMeta("The Water Cycle", "yarn", None, 6, 6, 6, 3, 3, None, None, None, 5),
    "Hurricane": SongMeta("The Water Cycle", "yarn", 5, 4, 3, None, 3, 4, None, None, None, 4),
    "Liquidic Breakdown": SongMeta("The Water Cycle", "yarn", 3, 4, 5, None, 5, 4, None, None, None, None),
    "Rain": SongMeta("The Water Cycle", "yarn", None, 4, None, None, 4, 5, None, None, None, None),
    "Surface Wind": SongMeta("The Water Cycle", "yarn", 3, 3, 3, 3, 5, 4, 0, None, None, None),
    "Thunderstorm": SongMeta("The Water Cycle", "yarn", 1, 2, 3, None, 1, 1, None, None, None, None),
    "Tsunami": SongMeta("The Water Cycle", "yarn", 3, 3, 6, None, 5, 5, None, None, None, None),
    "Twilight Ocean": SongMeta("The Water Cycle", "yarn", 3, 3, 3, None, 5, 4, None, None, None, None),
    "Water's Under": SongMeta("The Water Cycle", "yarn", None, 3, 4, None, 4, 4, None, None, None, None),
    "Born of Dirt": SongMeta("Assorted Metal 2", "yargdlc", 4, 2, 6, None, None, None, 0, None, None, 4),
    "Deceptive Consequences": SongMeta("Assorted Metal 2", "yargdlc", 4, 3, 6, None, None, None, None, None, None, 4),
    "Event Horizon": SongMeta("Assorted Metal 2", "yargdlc", 3, 4, 4, None, 1, 1, 0, 0, 0, 4),
    "Funeral Waltz": SongMeta("Assorted Metal 2", "yargdlc", 1, 1, 1, None, 2, 2, 1, 1, 1, 1),
    "I.E.D. Vanflip": SongMeta("Assorted Metal 2", "yargdlc", 4, 4, 7, 7, None, None, 0, 0, 0, 0),
    "Introspective Nightmares": SongMeta("Assorted Metal 2", "yargdlc", 6, 6, 7, None, 0, 0, 0, 0, 0, 6),
    "Mr. Jackalope (And His Restless Haunting) / When Days End": SongMeta("Assorted Metal 2", "yargdlc", 6, 2, 4, None, None, None, None, None, None, 4),
    "The Lonesome Tongues": SongMeta("Assorted Metal 2", "yargdlc", 4, 3, 5, None, 0, 1, 0, 0, 0, 3),
    "Train Wreck": SongMeta("Assorted Metal 2", "yargdlc", 2, 1, 7, None, None, None, 0, 0, None, 2),
    "Angels We Have Heard on High": SongMeta("Christmas Keys 2", "yargdlc", None, 2, None, None, 3, 3, None, None, None, None),
    "O Come, All Ye Faithful": SongMeta("Christmas Keys 2", "yargdlc", None, 1, None, None, 2, 2, None, None, None, None),
    "Shchedryk": SongMeta("Christmas Keys 2", "yargdlc", None, 3, None, None, 3, 3, None, None, None, None),
    "Silent Night": SongMeta("Christmas Keys 2", "yargdlc", None, 0, None, None, 1, 1, None, None, None, None),
    "The First Noël": SongMeta("Christmas Keys 2", "yargdlc", None, 2, None, None, 2, 2, None, None, None, None),
    "The Twelve Days of Christmas": SongMeta("Christmas Keys 2", "yargdlc", None, 2, None, None, 2, 2, None, None, None, None),
}

#Example on using the Songs Dictionary
#
#for name, data in Songs.items():
#    print("Song Name: " + name)
#    print("5 Fret Guitar Diff: " + str(data.guitar5F))
#    print("5 Fret Bass Diff: " + str(data.bass5F))
#
#If you want to use the Songs Dict in other file add to top of file
#
#from .songinfo import Songs
    
    