from typing import NamedTuple, Optional, Dict

class SongMeta(NamedTuple):
    """Contains difficulty information, Use None for unsupported intsruments"""

    songname: str
    artistname: str
    group: str
    source: str
    guitar5F: Optional[int]
    bass5F: Optional[int]
    drums: Optional[int]
    drumsElite: Optional[int]
    keys5F: Optional[int]
    keysPro: Optional[int]
    vocals: Optional[int]
    harmony2: Optional[int]
    harmony3: Optional[int]
    rhythm5F: Optional[int]

Songs: Dict[int, SongMeta] = {
    1: SongMeta("106", "Frostbitt", "YARG Official Setlist", "yarg", 5, 4, 4, 4, None, None, 2, 2, 2, None),
    2: SongMeta("1nput This 2 Y0ur Spine", "Camellia", "YARG Official Setlist", "yarg", 6, 4, 6, 6, 6, 6, 0, None, None, None),
    3: SongMeta("322", "Creo", "YARG Official Setlist", "yarg", 4, 4, 5, None, 3, 3, 0, None, None, None),
    4: SongMeta("A Visitant (feat. Victor Borba)", "RO1", "YARG Official Setlist", "yarg", 3, 1, 5, None, 6, 6, 4, 4, None, None),
    5: SongMeta("About the Author", "The Sterns", "YARG Official Setlist", "yarg", 3, 2, 2, None, 1, 1, 5, 5, 5, None),
    6: SongMeta("The Afterparty", "Portraits of Tracy", "YARG Official Setlist", "yarg", 3, 1, 2, None, 2, 3, 3, 3, 3, None),
    7: SongMeta("Al Gore Rhythm", "Blight Town", "YARG Official Setlist", "yarg", 5, 4, 5, None, None, None, 5, 5, 5, None),
    8: SongMeta("Alibi", "Vera Kay", "YARG Official Setlist", "yarg", 3, 3, 6, None, 0, 0, 4, 4, 4, None),
    9: SongMeta("All of a Sudden", "Adamic", "YARG Official Setlist", "yarg", 3, 3, 4, None, 2, 3, 1, 1, None, None),
    10: SongMeta("Allure", "Shibito", "YARG Official Setlist", "yarg", 5, 5, 6, None, 0, 0, 2, 2, 2, None),
    11: SongMeta("Avatar the Last Cakebender", "Palette Knife", "YARG Official Setlist", "yarg", 4, 3, 5, None, 4, 4, 4, 4, 4, None),
    12: SongMeta("Avatara", "Heteromorphic Zoo", "YARG Official Setlist", "yarg", 2, 2, 4, 4, 2, 2, 0, 0, None, None),
    13: SongMeta("Bathe in Blood", "Parasiticide", "YARG Official Setlist", "yarg", 6, 2, 6, None, None, None, 0, None, None, None),
    14: SongMeta("Bedroom Community", "Glass Beach", "YARG Official Setlist", "yarg", 3, 3, 3, 3, 5, 5, 3, 3, 3, None),
    15: SongMeta("Better Off Worse (feat. Flower)", "CircusP", "YARG Official Setlist", "yarg", 1, 2, 2, None, 3, 3, 6, 6, 6, None),
    16: SongMeta("Beverly", "Used to Be Valentines", "YARG Official Setlist", "yarg", 2, 2, 2, None, None, None, 2, 2, 2, None),
    17: SongMeta("Blue (feat. Miori Celesta)", "InVerSe", "YARG Official Setlist", "yarg", 3, 5, 4, None, 5, 5, 5, 5, 5, None),
    18: SongMeta("Boom Slayer (feat. Scott Foster Harris)", "Boom Kitty", "YARG Official Setlist", "yarg", 3, 3, 4, None, 2, 2, 3, 3, None, None),
    19: SongMeta("Bottleneck", "Groundlift", "YARG Official Setlist", "yarg", 5, 5, 5, None, None, None, 3, 3, None, None),
    20: SongMeta("Buds", "Troubled Minds", "YARG Official Setlist", "yarg", 2, 1, 2, None, None, None, 2, 2, 2, None),
    21: SongMeta("Butterflies", "Kingseeker", "YARG Official Setlist", "yarg", 3, 3, 4, 4, None, None, 1, 1, 1, None),
    22: SongMeta("Chocolate Rain (Sweet Like Chocolate Remix)", "Tay Zonday", "YARG Official Setlist", "yarg", 2, 2, 2, None, 4, 4, 4, 4, 4, None),
    23: SongMeta("Choked Up", "See You at Rogers", "YARG Official Setlist", "yarg", 3, 1, 2, 2, 3, 4, 4, 4, 4, None),
    24: SongMeta("Circles", "Thousand Thoughts", "YARG Official Setlist", "yarg", 3, 3, 3, None, 0, 0, 3, 3, 3, None),
    25: SongMeta("Cowboy Tanaka", "Atomic Guava", "YARG Official Setlist", "yarg", 4, 3, 5, None, 5, 5, 4, 4, 4, None),
    26: SongMeta("Cruisin'", "raphaelgoulart", "YARG Official Setlist", "yarg", 5, 3, 4, None, 3, 3, None, None, None, None),
    27: SongMeta("Discipline", "Nine Inch Nails", "YARG Official Setlist", "yarg", 3, 2, 2, 2, 2, 2, 3, 3, 3, None),
    28: SongMeta("Do", "Garlagan", "YARG Official Setlist", "yarg", 3, 4, 5, None, 4, 4, 6, 6, None, None),
    29: SongMeta("Don't Look!", "Prismia", "YARG Official Setlist", "yarg", 2, 3, 4, None, 6, 6, 1, 1, 1, None),
    30: SongMeta("Don't Spook the Owl", "Kidd Judo", "YARG Official Setlist", "yarg", 3, 3, 4, None, None, None, 4, 4, 4, None),
    31: SongMeta("Dreamweaver", "Glass Guillotine", "YARG Official Setlist", "yarg", 3, 3, 4, 4, None, None, 0, 0, 0, None),
    32: SongMeta("Duvet Thief", "The Covasettes", "YARG Official Setlist", "yarg", 2, 2, 4, None, 1, 2, 3, 3, 3, None),
    33: SongMeta("Eleven", "Last Dinosaurs", "YARG Official Setlist", "yarg", 2, 2, 3, None, 0, 0, 2, 2, 2, None),
    34: SongMeta("Emperor Rising", "Krilloan", "YARG Official Setlist", "yarg", 5, 5, 6, None, None, None, 4, 4, 4, None),
    35: SongMeta("Empires", "Electric Swing Circus", "YARG Official Setlist", "yarg", 2, 1, 4, None, 4, 4, 4, 4, 4, None),
    36: SongMeta("Everybody Do the Flop", "LilDeuceDeuce", "YARG Official Setlist", "yarg", 4, 3, 5, None, 4, 4, 5, 5, 5, None),
    37: SongMeta("Exeter", "Another One Down!", "YARG Official Setlist", "yarg", 3, 4, 4, None, 0, 0, 2, 2, 2, None),
    38: SongMeta("Fine", "Lemon Demon", "YARG Official Setlist", "yarg", 4, 2, 4, 4, 2, 2, 4, 4, 4, None),
    39: SongMeta("Flight of the Bumblebee", "FamilyJules", "YARG Official Setlist", "yarg", 6, 3, 6, None, None, None, None, None, None, None),
    40: SongMeta("Formless Collective", "A Pretext to Human Suffering", "YARG Official Setlist", "yarg", 6, 5, 8, None, None, None, 0, 0, 0, None),
    41: SongMeta("Frank Scored a Video Game", "Max Boras", "YARG Official Setlist", "yarg", 6, 5, 5, None, None, None, None, None, None, None),
    42: SongMeta("Front Row Seats (To Watching Your World Burn)", "FoundiT", "YARG Official Setlist", "yarg", 2, 2, 5, None, 1, 1, 3, 3, 3, None),
    43: SongMeta("The Game", "RinRin", "YARG Official Setlist", "yarg", 4, 2, 4, 4, 2, 2, 3, 3, 3, None),
    44: SongMeta("God Only Knows (feat. Kasane Teto)", "Bitbreaker", "YARG Official Setlist", "yarg", 5, 5, 5, None, 4, 4, 3, 3, 3, None),
    45: SongMeta("Guess I'll Never Know", "TrackTribe", "YARG Official Setlist", "yarg", 1, 0, 3, None, 0, 0, 2, 2, 2, None),
    46: SongMeta("Half Measures", "Aaron Musslewhite", "YARG Official Setlist", "yarg", 0, 0, 1, None, 0, 1, 6, 6, 6, None),
    47: SongMeta("Human God", "Hadson", "YARG Official Setlist", "yarg", 4, 3, 3, None, None, None, 1, 1, 1, None),
    48: SongMeta("I Don't Wanna Talk", "Carter Vail", "YARG Official Setlist", "yarg", 3, 3, 3, None, 2, 2, 2, 2, 2, None),
    49: SongMeta("I Wish That I Could Fall (feat. GUMI)", "Jamie Paige", "YARG Official Setlist", "yarg", 3, 5, 1, None, 5, 5, 5, 5, 5, None),
    50: SongMeta("I'm a Bug", "Fries on the Side", "YARG Official Setlist", "yarg", 1, 1, 3, None, 5, 5, 2, 2, 2, None),
    51: SongMeta("Igowallah", "Daniel Thrasher", "YARG Official Setlist", "yarg", 0, 2, 5, None, 0, 0, 4, 4, 4, None),
    52: SongMeta("In My Head", "Halfway to Michigan", "YARG Official Setlist", "yarg", 1, 1, 2, None, None, None, 2, 2, 2, None),
    53: SongMeta("Is This What You Wanted", "Scro", "YARG Official Setlist", "yarg", 4, 1, 2, None, 2, 2, 5, 5, 5, None),
    54: SongMeta("It Kills Me", "Roomie", "YARG Official Setlist", "yarg", 2, 2, 4, None, 1, 2, 3, 3, 3, None),
    55: SongMeta("Jenny B", "Bumblefoot", "YARG Official Setlist", "yarg", 7, 4, 2, 2, None, None, 5, None, None, None),
    56: SongMeta("John, Take Me with You", "JW Francis", "YARG Official Setlist", "yarg", 2, 2, 2, None, None, None, 2, 2, 2, None),
    57: SongMeta("Join the Club", "Tilly Louise", "YARG Official Setlist", "yarg", 3, 2, 2, None, 3, 3, 3, 3, 3, None),
    58: SongMeta("Languish", "Our Common Collapse", "YARG Official Setlist", "yarg", 4, 3, 5, 5, 2, 2, 0, 0, 0, None),
    59: SongMeta("Long in the Tooth", "Flying Raccoon Suit", "YARG Official Setlist", "yarg", 5, 3, 5, 5, 3, 3, 2, 2, 2, None),
    60: SongMeta("Luminaire", "insaneintherainmusic", "YARG Official Setlist", "yarg", 3, 3, 7, None, 5, 5, None, None, None, None),
    61: SongMeta("Marlboro Mountain", "Sweet Bike", "YARG Official Setlist", "yarg", 3, 3, 3, None, 0, 0, 3, 3, 3, None),
    62: SongMeta("The Masquerade", "Cantervice", "YARG Official Setlist", "yarg", 4, 4, 4, None, 5, 5, 2, 2, 2, None),
    63: SongMeta("Mass Gap", "Mindiode", "YARG Official Setlist", "yarg", 6, 6, 6, None, 6, 7, None, None, None, None),
    64: SongMeta("Moonlight Sonata 3rd Mvt (Big Band Version)", "The 8-Bit Big Band", "YARG Official Setlist", "yarg", 3, 5, 7, None, 6, 6, None, None, None, None),
    65: SongMeta("Need 2", "Pinegrove", "YARG Official Setlist", "yarg", 3, 0, 0, None, 2, 2, 1, 1, 1, None),
    66: SongMeta("The New World Disorder", "Höwler", "YARG Official Setlist", "yarg", 7, 7, 6, 6, None, None, 3, 3, 3, None),
    67: SongMeta("No Nations", "Jets Overhead", "YARG Official Setlist", "yarg", 0, 1, 0, None, 0, 0, 1, 1, 1, None),
    68: SongMeta("No Remedy", "Levia", "YARG Official Setlist", "yarg", 1, 1, 3, None, 3, 3, 2, 2, 2, None),
    69: SongMeta("Nomu", "Good Kid", "YARG Official Setlist", "yarg", 3, 2, 3, None, None, None, 5, 5, 5, None),
    70: SongMeta("Numb the Mind", "NyxTheShield", "YARG Official Setlist", "yarg", 1, 0, 2, None, 0, 0, 2, None, None, None),
    71: SongMeta("Oh, Krissy Baby!", "WhyLucas", "YARG Official Setlist", "yarg", 3, 2, 2, None, 3, 3, 4, 4, 4, None),
    72: SongMeta("Oopsie Daisy", "JubyPhonic", "YARG Official Setlist", "yarg", 1, 3, 2, None, 2, 2, 3, 3, 3, None),
    73: SongMeta("Over Again", "Alex Sandra", "YARG Official Setlist", "yarg", 2, 1, 2, None, 1, 1, 5, 5, 5, None),
    74: SongMeta("Overdrive", "Vessel", "YARG Official Setlist", "yarg", 3, 2, 3, None, None, None, 3, None, None, None),
    75: SongMeta("Oxygen", "Marta Vega", "YARG Official Setlist", "yarg", 2, 1, 2, None, 2, 2, 2, 2, 2, None),
    76: SongMeta("Participation Trophy Wife", "Thanks! I Hate It", "YARG Official Setlist", "yarg", 4, 3, 3, None, None, None, 3, 3, None, None),
    77: SongMeta("Pixel Galaxy", "Snail's House", "YARG Official Setlist", "yarg", 6, 2, 4, None, 3, 3, None, None, None, None),
    78: SongMeta("Pizza Rolls", "Bottom Bunk", "YARG Official Setlist", "yarg", 5, 1, 2, 2, None, None, 2, 2, 2, None),
    79: SongMeta("Plastic Boogie", "King Gizzard and the Lizard Wizard", "YARG Official Setlist", "yarg", 3, 3, 1, None, 1, 1, 2, 2, 2, None),
    80: SongMeta("Poser", "Luminism", "YARG Official Setlist", "yarg", 4, 3, 3, None, None, None, 4, 4, 4, None),
    81: SongMeta("Positively Clark Street", "Telethon", "YARG Official Setlist", "yarg", 4, 2, 2, None, 2, 2, 4, 4, 4, None),
    82: SongMeta("Queen of the Night", "The Vanished People", "YARG Official Setlist", "yarg", 3, 4, 3, None, 3, 3, 4, 4, 4, None),
    83: SongMeta("Runnin Man", "Stone Deep", "YARG Official Setlist", "yarg", 3, 3, 5, 5, None, None, 0, 0, 0, None),
    84: SongMeta("Sadness (feat. Sapphire Noel)", "Heartsick", "YARG Official Setlist", "yarg", 2, 2, 5, None, 2, 2, 2, 2, None, None),
    85: SongMeta("Salt the Wound", "Surefire", "YARG Official Setlist", "yarg", 3, 3, 6, None, 0, 0, 0, 0, 0, None),
    86: SongMeta("Seasons (feat. Shiki Miyoshino)", "Alohaii", "YARG Official Setlist", "yarg", 2, 1, 0, None, 1, 2, 3, 3, None, None),
    87: SongMeta("Show Ya", "Nana Asteria", "YARG Official Setlist", "yarg", 2, 0, 2, None, 2, 2, 3, 3, 3, None),
    88: SongMeta("Smile for Me", "The Robot's Guide to Living", "YARG Official Setlist", "yarg", 4, 2, 4, None, None, None, 3, 3, 3, None),
    89: SongMeta("Song of November", "Frantic Memories", "YARG Official Setlist", "yarg", 4, 4, 4, None, 1, 1, 3, 3, 3, None),
    90: SongMeta("Spirit", "Practically People", "YARG Official Setlist", "yarg", 2, 1, 1, None, 2, 2, 3, 3, 3, None),
    91: SongMeta("Splinter", "FIG", "YARG Official Setlist", "yarg", 2, 0, 1, None, 2, 3, 3, 3, 3, None),
    92: SongMeta("Stowaway Ants", "Alpha Boötis", "YARG Official Setlist", "yarg", 3, 2, 4, None, 4, 4, 3, 3, 3, None),
    93: SongMeta("Strangers Once Again (feat. Treb and Ofir Tabakov)", "Tanger", "YARG Official Setlist", "yarg", 4, 3, 6, None, 4, 6, 5, 5, 5, None),
    94: SongMeta("Stress", "Jim's Big Ego", "YARG Official Setlist", "yarg", 5, 5, 3, 3, 5, 5, 4, 4, 4, None),
    95: SongMeta("Sweet Victory", "Bob Kulick and David Glen Eisley", "YARG Official Setlist", "yarg", 3, 1, 2, None, 3, 3, 3, 3, 3, None),
    96: SongMeta("Synthespian", "Prototype", "YARG Official Setlist", "yarg", 5, 5, 6, None, None, None, 2, 2, None, None),
    97: SongMeta("They Call", "Auris", "YARG Official Setlist", "yarg", 4, 4, 4, None, None, None, 2, 2, 2, None),
    98: SongMeta("Time", "Vandalheart", "YARG Official Setlist", "yarg", 3, 2, 4, 4, 0, 0, 3, 3, 3, None),
    99: SongMeta("To Let Go", "NateWantsToBattle", "YARG Official Setlist", "yarg", 3, 3, 4, None, 1, 1, 4, 4, 4, None),
    100: SongMeta("Vehemence", "Reo", "YARG Official Setlist", "yarg", 6, 4, 6, None, None, None, None, None, None, None),
    101: SongMeta("Voidwalker", "Inflicted", "YARG Official Setlist", "yarg", 4, 3, 5, None, 0, 0, 0, 0, 0, None),
    102: SongMeta("We All Float Down Here", "Four Year Strong", "YARG Official Setlist", "yarg", 6, 4, 5, None, None, None, 2, 2, None, None),
    103: SongMeta("Burn", "Troubled Minds", "Assorted Rock 1", "yargdlc", 1, 0, 1, None, None, None, 1, 1, 1, None),
    104: SongMeta("Drunken Monday (Freeway Mix)", "Fisher Wagg", "Assorted Rock 1", "yargdlc", 3, 2, 1, 2, None, None, 3, 3, 3, 3),
    105: SongMeta("Middle of the City Road", "Walter Ralts", "Assorted Rock 1", "yargdlc", 3, 3, 2, 2, 1, 1, None, None, None, 1),
    106: SongMeta("Moonlight", "Chill", "Assorted Rock 1", "yargdlc", 2, 0, None, None, 1, 1, 1, None, None, None),
    107: SongMeta("Rock Thing", "Creo", "Assorted Rock 1", "yargdlc", 3, 1, 3, None, 4, 4, None, None, None, None),
    108: SongMeta("Simplicity", "Scott Buckley", "Assorted Rock 1", "yargdlc", 1, 0, 1, None, 2, 2, None, None, None, None),
    109: SongMeta("Turtleneck", "TrackTribe", "Assorted Rock 1", "yargdlc", 3, 1, 3, None, 2, 2, None, None, None, None),
    110: SongMeta("By the Seaside (feat. Kitsui Akira)", "Kirara Magic", "Assorted Electronic 1", "yargdlc", 3, 1, 6, None, 3, 3, 3, 3, None, None),
    111: SongMeta("Feel Good", "Syn Cole", "Assorted Electronic 1", "yargdlc", 2, 1, 1, None, 2, 3, 2, 2, None, None),
    112: SongMeta("Ghost", "Aaron Musslewhite", "Assorted Electronic 1", "yargdlc", 3, 1, 2, None, 2, 2, 4, 4, None, None),
    113: SongMeta("Radioactive", "Waterflame", "Assorted Electronic 1", "yargdlc", 2, 6, 5, 5, 4, 5, 0, None, None, 2),
    114: SongMeta("Rot for Clout (feat. Kasane Teto)", "Jamie Paige", "Assorted Electronic 1", "yargdlc", 3, 4, 4, None, 4, 5, 6, 6, None, 3),
    115: SongMeta("Say It Back", "tv room", "Assorted Electronic 1", "yargdlc", 4, 2, 4, None, 4, 5, 5, 5, None, None),
    116: SongMeta("Space and Time! (feat. Jelly Hoshiumi)", "SO89", "Assorted Electronic 1", "yargdlc", 7, 2, 0, None, 4, 5, 3, 3, 3, None),
    117: SongMeta("Angel in Disguise (feat. Kitsui Akira)", "Alohaii", "SUMMERTIDE", "yargdlc", 2, 2, 2, None, 3, 3, 5, 5, None, None),
    118: SongMeta("Cinnamon (feat. Miori Celesta and Yuuna Nini)", "Alohaii", "SUMMERTIDE", "yargdlc", 2, 1, 3, None, 2, 2, 6, 6, 6, None),
    119: SongMeta("Embrace (feat. Kiyon)", "Alohaii", "SUMMERTIDE", "yargdlc", 5, 3, 2, None, 3, 3, 4, 4, 4, 4),
    120: SongMeta("Heart of Glass (feat. Rachie)", "Alohaii", "SUMMERTIDE", "yargdlc", 2, 3, 4, None, 3, 3, 6, 6, None, None),
    121: SongMeta("Hopeless Romantic (feat. JubyPhonic)", "Alohaii", "SUMMERTIDE", "yargdlc", 0, 0, 2, None, 2, 3, 3, 3, 3, None),
    122: SongMeta("Love Me Not (feat. Tofie)", "Alohaii", "SUMMERTIDE", "yargdlc", 4, 0, 1, None, 2, 2, 4, 4, 4, None),
    123: SongMeta("Magazines (feat. Nia Suzune)", "Alohaii", "SUMMERTIDE", "yargdlc", 3, 2, 2, None, 1, 3, 5, 5, 5, None),
    124: SongMeta("One Step at a Time (feat. Miori Celesta)", "Alohaii", "SUMMERTIDE", "yargdlc", 3, 2, 3, None, 2, 2, 3, 3, 3, 6),
    125: SongMeta("Rose (feat. Ember Amane)", "Alohaii", "SUMMERTIDE", "yargdlc", 2, 1, 1, None, 2, 2, 3, 3, 3, None),
    126: SongMeta("Through the Night (feat. Yuuka Bear)", "Alohaii", "SUMMERTIDE", "yargdlc", 5, 4, 2, None, 2, 2, 4, 4, 4, 4),
    127: SongMeta("Cars", "JW Francis", "WANDERKID", "yargdlc", 3, 1, None, None, None, None, 2, 2, 2, None),
    128: SongMeta("Don't Fall Apart", "JW Francis", "WANDERKID", "yargdlc", 3, 2, 2, None, 0, 0, 2, 2, None, None),
    129: SongMeta("Fake It Till You Make It", "JW Francis", "WANDERKID", "yargdlc", 1, 0, 1, 1, 0, 0, 1, None, None, None),
    130: SongMeta("Holy Mountain", "JW Francis", "WANDERKID", "yargdlc", 3, 4, 4, None, 2, 2, 4, None, None, 4),
    131: SongMeta("I Love You", "JW Francis", "WANDERKID", "yargdlc", 2, 2, 2, None, 1, 2, 2, 2, None, None),
    132: SongMeta("I'm Probably a Ghost", "JW Francis", "WANDERKID", "yargdlc", 3, 2, 4, 4, 0, 0, 2, None, None, None),
    133: SongMeta("Make Another Record", "JW Francis", "WANDERKID", "yargdlc", 3, 2, 4, None, 1, 1, 2, None, None, None),
    134: SongMeta("Maybe", "JW Francis", "WANDERKID", "yargdlc", 1, 3, 4, None, 2, 2, 4, 4, 4, None),
    135: SongMeta("Only with You", "JW Francis", "WANDERKID", "yargdlc", 1, 2, 1, 1, 1, 2, 3, 3, 3, None),
    136: SongMeta("Wanderkid", "JW Francis", "WANDERKID", "yargdlc", 1, 3, 4, None, 0, 0, 4, 4, None, None),
    137: SongMeta("Bridal Chorus", "Richard Wagner", "Classical Keys Pack 1", "yargdlc", None, 3, None, None, 3, 3, None, None, None, None),
    138: SongMeta("Clair de Lune", "Claude Debussy", "Classical Keys Pack 1", "yargdlc", None, 2, None, None, 2, 2, None, None, None, None),
    139: SongMeta("Entrance of the Gladiators", "Julius Fučík", "Classical Keys Pack 1", "yargdlc", None, 4, None, None, 4, 4, None, None, None, None),
    140: SongMeta("Maple Leaf Rag", "Scott Joplin", "Classical Keys Pack 1", "yargdlc", None, 3, None, None, 5, 5, None, None, None, None),
    141: SongMeta("Marche Funèbre", "Frédéric Chopin", "Classical Keys Pack 1", "yargdlc", None, 2, None, None, 2, 2, None, None, None, None),
    142: SongMeta("Scherzo No. 1", "Frédéric Chopin", "Classical Keys Pack 1", "yargdlc", None, 5, None, None, 7, 7, None, None, None, None),
    "Frère Jacques": SongMeta("Children's Keys Pack 1", "yargdlc", None, 0, None, None, 1, 1, None, None, None, None),
    "Happy Birthday to You": SongMeta("Children's Keys Pack 1", "yargdlc", None, 0, None, None, 0, 0, None, None, None, None),
    "Mary Had a Little Lamb": SongMeta("Children's Keys Pack 1", "yargdlc", None, 0, None, None, 0, 0, None, None, None, None),
    "Rock-a-Bye Baby": SongMeta("Children's Keys Pack 1", "yargdlc", None, 1, None, None, 1, 1, None, None, None, None),
    "Row, Row, Row Your Boat": SongMeta("Children's Keys Pack 1", "yargdlc", None, 0, None, None, 1, 1, None, None, None, None),
    "Twinkle, Twinkle, Little Star": SongMeta("Children's Keys Pack 1", "yargdlc", None, 0, None, None, 0, 0, None, None, None, None),
    "Dance of the Sugar Plum Fairy": SongMeta("Christmas Keys 1", "yargdlc", None, 4, None, None, 4, 4, None, None, None, None),
    "Deck the Halls": SongMeta("Christmas Keys 1", "yargdlc", None, 2, None, None, 3, 3, None, None, None, None),
    "Good King Wenceslas": SongMeta("Christmas Keys 1", "yargdlc", None, 0, None, None, 0, 0, None, None, None, None),
    "Jingle Bells": SongMeta("Christmas Keys 1", "yargdlc", None, 3, None, None, 2, 2, None, None, None, None),
    "Jolly Old Saint Nicholas": SongMeta("Christmas Keys 1", "yargdlc", None, 0, None, None, 1, 1, None, None, None, None),
    "Joy to the World": SongMeta("Christmas Keys 1", "yargdlc", None, 1, None, None, 2, 2, None, None, None, None),
    "Amelioration": SongMeta("YARN Pack 1", "yarn", 6, 4, 6, None, None, None, None, None, None, None),
    "Burn": SongMeta("YARN Pack 1", "yarn", 2, 1, None, None, None, None, None, None, None, 2),
    "Eviternal": SongMeta("YARN Pack 1", "yarn", 5, 4, 6, None, 4, 5, 5, 5, 5, None),
    "Fearfulness": SongMeta("YARN Pack 1", "yarn", 10, None, None, None, None, None, None, None, None, None),
    "How": SongMeta("YARN Pack 1", "yarn", 4, None, None, None, None, None, None, None, None, None),
    "I'm mindless :3": SongMeta("YARN Pack 1", "yarn", 8, None, None, None, None, None, None, None, None, None),
    "Reaper (2023 Remaster)": SongMeta("YARN Pack 1", "yarn", 6, 3, 6, None, None, None, None, None, None, None),
    "Second Wind": SongMeta("YARN Pack 1", "yarn", 3, 6, 6, 6, 3, 3, None, None, None, None),
    "Ways of Torment": SongMeta("YARN Pack 1", "yarn", 5, None, None, None, None, None, None, None, None, None),
    "Whispers (Rose Ver.)": SongMeta("YARN Pack 1", "yarn", 2, 1, 2, None, None, None, None, None, None, None),
    "Abomination": SongMeta("Mini-Wave 0", "yarn", 4, None, 6, None, None, None, 1, None, None, None),
    "Back To School Bitches (Kiraken-G Remix)": SongMeta("Mini-Wave 0", "yarn", 10, None, None, None, None, None, None, None, None, None),
    "Brain Implosion Energy Drink (feat. Kasane Teto and Eleanor Forte)": SongMeta("Mini-Wave 0", "yarn", 2, 1, 3, None, 1, 1, 4, 4, None, None),
    "Code 75": SongMeta("Mini-Wave 0", "yarn", 4, 2, 4, None, 3, 3, 4, 4, 4, None),
    "Dance Mr. Funnybones (LOOP)": SongMeta("Mini-Wave 0", "yarn", 1, 1, 2, None, None, None, None, None, None, 0),
    "Hard Licker": SongMeta("Mini-Wave 0", "yarn", 4, 4, 5, None, None, None, None, None, None, None),
    "help, the sillies are after me!1!!!1": SongMeta("Mini-Wave 0", "yarn", None, 3, 4, 4, 4, 4, None, None, None, None),
    "Nice Logo": SongMeta("Mini-Wave 0", "yarn", 2, 1, 2, None, 2, 2, 0, None, None, None),
    "opus_10": SongMeta("Mini-Wave 0", "yarn", None, 5, None, None, 6, 6, None, None, None, None),
    "Still Got It": SongMeta("Mini-Wave 0", "yarn", 2, 2, 2, None, None, None, None, None, None, None),
    "Wou Wou Wou": SongMeta("Mini-Wave 0", "yarn", 6, None, None, None, None, None, 0, None, None, None),
    "Control": SongMeta("Assorted Metal 1", "yargdlc", 3, 3, 2, None, 3, 3, 3, 3, 3, 3),
    "Full Body Plutonium": SongMeta("Assorted Metal 1", "yargdlc", 4, 3, 5, 5, None, None, 3, 3, None, 3),
    "Harbinger of Pestilence": SongMeta("Assorted Metal 1", "yargdlc", 6, 3, 6, 6, None, None, None, None, None, 4),
    "Hell": SongMeta("Assorted Metal 1", "yargdlc", 4, 2, 5, None, 0, 0, 3, 3, 3, 4),
    "Simple Folds": SongMeta("Assorted Metal 1", "yargdlc", 3, 3, 4, None, 3, 3, 4, 4, 4, 3),
    "Sleep Cycles": SongMeta("Assorted Metal 1", "yargdlc", 3, 3, 4, None, 2, 2, 1, 1, 1, 3),
    "The Mortal Plane": SongMeta("Assorted Metal 1", "yargdlc", 5, 3, 5, None, 5, 5, None, None, None, 4),
    "What You Really Want": SongMeta("Assorted Metal 1", "yargdlc", 5, 4, 3, None, 5, 5, 4, 4, 4, 5),
    "Chopsticks": SongMeta("Children's Keys Pack 2", "yargdlc", None, 1, None, None, 2, 2, None, None, None, None),
    "Hey Diddle Diddle": SongMeta("Children's Keys Pack 2", "yargdlc", None, 0, None, None, 0, 0, None, None, None, None),
    "Old MacDonald Had a Farm": SongMeta("Children's Keys Pack 2", "yargdlc", None, 0, None, None, 1, 1, None, None, None, None),
    "Over the River and Through the Woods": SongMeta("Children's Keys Pack 2", "yargdlc", None, 1, None, None, 1, 1, None, None, None, None),
    "Pop Goes the Weasel": SongMeta("Children's Keys Pack 2", "yargdlc", None, 1, None, None, 0, 0, None, None, None, None),
    "Three Blind Mice": SongMeta("Children's Keys Pack 2", "yargdlc", None, 0, None, None, 1, 1, None, None, None, None),
    "Funiculì, Funiculà": SongMeta("Classical Keys Pack 2", "yargdlc", None, 3, None, None, 3, 3, None, None, None, None),
    "Hungarian Rhapsody No. 2": SongMeta("Classical Keys Pack 2", "yargdlc", None, 6, None, None, 7, 7, None, None, None, None),
    "Minuet in G Major": SongMeta("Classical Keys Pack 2", "yargdlc", None, 1, None, None, 1, 1, None, None, None, None),
    "Piano Sonata No. 16, Mvt. I: Allegro": SongMeta("Classical Keys Pack 2", "yargdlc", None, 5, None, None, 5, 5, None, None, None, None),
    "The Well-Tempered Clavier Book 1 No. 1: Prelude and Fugue in C Major": SongMeta("Classical Keys Pack 2", "yargdlc", None, 0, None, None, 2, 2, None, None, None, None),
    "Twelfth Street Rag": SongMeta("Classical Keys Pack 2", "yargdlc", None, 3, None, None, 6, 6, None, None, None, None),
    "Below the Waves": SongMeta("FX4", "yarn", 4, 4, 5, None, None, None, None, None, None, None),
    "First Flight": SongMeta("FX4", "yarn", 5, 6, 6, None, None, None, None, None, None, None),
    "HBO Feature Presentation": SongMeta("FX4", "yarn", 2, 0, 2, None, None, None, None, None, None, None),
    "Incident Zero": SongMeta("FX4", "yarn", 4, 5, 6, None, None, None, None, None, None, None),
    "Journey into the Rift": SongMeta("FX4", "yarn", 5, 4, 7, None, None, None, None, None, None, None),
    "Reconstruct": SongMeta("FX4", "yarn", 5, 3, 3, None, None, None, None, None, None, None),
    "Singularity": SongMeta("FX4", "yarn", 5, 4, 6, None, None, None, None, None, None, None),
    "The Time Vampire": SongMeta("FX4", "yarn", 5, 4, 6, None, None, None, None, None, None, None),
    "Undone": SongMeta("FX4", "yarn", 4, 4, 5, None, None, None, None, None, None, None),
    "Weapon": SongMeta("FX4", "yarn", 4, 4, 6, None, None, None, None, None, None, None),
    "Abyss of Time": SongMeta("Abyss of Time", "yarn", 3, 2, 3, None, None, None, 3, 3, 3, None),
    "Aphrodite": SongMeta("Abyss of Time", "yarn", 4, 4, 5, None, None, None, 2, 2, None, None),
    "Bleed Your Hate Out": SongMeta("Abyss of Time", "yarn", 4, 4, 5, None, None, None, 3, 3, None, None),
    "Death Drive": SongMeta("Abyss of Time", "yarn", 2, 3, 4, None, None, None, 3, 3, 3, None),
    "Desert Rose": SongMeta("Abyss of Time", "yarn", 3, 2, 3, None, None, None, 2, 2, None, None),
    "Destroyer of Worlds": SongMeta("Abyss of Time", "yarn", 3, 3, 5, None, None, None, 1, 1, 1, None),
    "Impossible": SongMeta("Abyss of Time", "yarn", 4, 4, 4, None, None, None, 3, 3, None, None),
    "Inertia": SongMeta("Abyss of Time", "yarn", 2, 1, 2, None, None, None, 3, 3, None, None),
    "Mind Like a Minefield": SongMeta("Abyss of Time", "yarn", 3, 3, 4, None, None, None, 4, 4, 4, None),
    "Scorch the Earth": SongMeta("Abyss of Time", "yarn", 3, 3, 4, None, None, None, 4, None, None, None),
    "Summer Rain": SongMeta("Abyss of Time", "yarn", 3, 2, 3, None, None, None, 3, None, None, None),
    "Swallow": SongMeta("Abyss of Time", "yarn", 2, 2, 3, None, None, None, 2, 2, 2, None),
    "The Penalty": SongMeta("Abyss of Time", "yarn", 5, 4, 6, None, None, None, 3, 3, None, None),
    "Unclear Warfare": SongMeta("Abyss of Time", "yarn", 3, 2, 3, None, None, None, 4, 4, 4, None),
    "We've Seen Better Days": SongMeta("Abyss of Time", "yarn", 2, 1, 2, None, None, None, 3, 3, 3, None),
    "200": SongMeta("Plastic Death", "yarn", 1, 1, 4, None, None, None, None, None, None, None),
    "Abyss Angel": SongMeta("Plastic Death", "yarn", 2, 1, 4, None, None, None, None, None, None, None),
    "Coelacanth": SongMeta("Plastic Death", "yarn", 3, 2, 3, None, None, None, None, None, None, None),
    "Commatose": SongMeta("Plastic Death", "yarn", 6, 2, 4, None, None, None, None, None, None, None),
    "Cul-de-Sac": SongMeta("Plastic Death", "yarn", 3, 1, 3, None, None, None, None, None, None, None),
    "Guitar Song": SongMeta("Plastic Death", "yarn", 1, 1, 3, None, None, None, None, None, None, None),
    "Motions": SongMeta("Plastic Death", "yarn", 2, 1, 3, None, None, None, None, None, None, None),
    "Puppy": SongMeta("Plastic Death", "yarn", 2, 1, 3, None, None, None, None, None, None, None),
    "Rare Animal": SongMeta("Plastic Death", "yarn", 3, 2, 3, None, None, None, None, None, None, None),
    "Slip under the Door": SongMeta("Plastic Death", "yarn", 3, 1, 3, None, None, None, None, None, None, None),
    "The CIA": SongMeta("Plastic Death", "yarn", 5, 1, 5, None, None, None, None, None, None, None),
    "The Killer": SongMeta("Plastic Death", "yarn", 1, 1, 2, None, None, None, None, None, None, None),
    "Whalefall": SongMeta("Plastic Death", "yarn", 3, 1, 6, None, None, None, None, None, None, None),
    "Dance Like an Idiot": SongMeta("Assorted Rock 2", "yargdlc", 4, 3, 2, 2, 4, 4, 4, 4, 4, 3),
    "Let Me Dance (feat. Miori Celesta)": SongMeta("Assorted Rock 2", "yargdlc", 5, 2, 1, None, 2, 3, 2, 2, 2, None),
    "Like I Used to Be": SongMeta("Assorted Rock 2", "yargdlc", 2, 2, 3, None, None, None, 1, 1, 1, None),
    "North Carolina": SongMeta("Assorted Rock 2", "yargdlc", 2, 0, 1, None, None, None, 1, 1, None, None),
    "Safehouse": SongMeta("Assorted Rock 2", "yargdlc", 5, 4, 5, None, 6, 6, 5, 5, 5, 4),
    "Surf Song": SongMeta("Assorted Rock 2", "yargdlc", 5, 3, 5, None, None, None, 2, 2, None, None),
    "Until the Wind Blows Us Away (feat. Leucinjel)": SongMeta("Assorted Rock 2", "yargdlc", 4, 2, 2, None, 0, 1, 2, 2, None, None),
    "All These Darlings and Now Me": SongMeta("YARN Pack 2", "yarn", 5, None, None, None, None, None, None, None, None, None),
    "Alternative Ego": SongMeta("YARN Pack 2", "yarn", 8, 6, 8, None, None, None, None, None, None, None),
    "Apple Fritter": SongMeta("YARN Pack 2", "yarn", 2, 2, 3, None, None, None, None, None, None, None),
    "BIRDBRAIN (feat. OK Glass and Kasane Teto)": SongMeta("YARN Pack 2", "yarn", 3, 3, 4, None, None, None, 5, None, None, None),
    "Country": SongMeta("YARN Pack 2", "yarn", 4, 0, 1, None, 2, 3, 3, 3, 3, None),
    "Desolate Memory": SongMeta("YARN Pack 2", "yarn", 4, None, 5, None, None, None, None, None, None, None),
    "Glass Beach": SongMeta("YARN Pack 2", "yarn", 3, 2, 4, None, None, None, None, None, None, None),
    "Keep Your Guard Up": SongMeta("YARN Pack 2", "yarn", 4, 3, 5, None, 4, 4, None, None, None, None),
    "Machine Love (feat. Kasane Teto)": SongMeta("YARN Pack 2", "yarn", 3, 3, 3, None, None, None, 4, None, None, None),
    "Madtown": SongMeta("YARN Pack 2", "yarn", 0, 3, 2, 2, 1, 1, 1, 1, None, 0),
    "Stranded": SongMeta("YARN Pack 2", "yarn", 4, 2, 5, None, None, None, None, None, None, None),
    "Underground Popstars": SongMeta("YARN Pack 2", "yarn", 3, 2, 2, None, None, None, 2, None, None, None),
    "999,999 / 1,000,000": SongMeta("The Slip", "yargdlc", 3, 2, 3, 3, 2, 2, 4, 4, 4, 1),
    "Corona Radiata": SongMeta("The Slip", "yargdlc", 1, 0, 0, 0, 0, 1, None, None, None, 0),
    "Demon Seed": SongMeta("The Slip", "yargdlc", 2, 1, 4, 4, 2, 2, 3, 3, 3, 1),
    "Echoplex": SongMeta("The Slip", "yargdlc", 3, 2, 4, 4, 0, 0, 2, 2, 2, 2),
    "Head Down": SongMeta("The Slip", "yargdlc", 4, 1, 4, 4, 4, 3, 2, 2, None, 3),
    "Letting You": SongMeta("The Slip", "yargdlc", 4, 2, 6, 6, 1, 1, 2, 2, 2, 4),
    "Lights in the Sky": SongMeta("The Slip", "yargdlc", 0, 0, None, None, 0, 1, 2, None, None, None),
    "The Four of Us Are Dying": SongMeta("The Slip", "yargdlc", 2, 2, 3, 3, 2, 2, None, None, None, 3),
    "Alive (feat. Jeremy Fagan)": SongMeta("YARN Pack 3", "yarn", 4, 3, 5, None, None, 1, 3, 3, 3, 3),
    "BUTCHER VANITY (ft. Yi Xi)": SongMeta("YARN Pack 3", "yarn", 1, 4, 4, None, None, None, 6, 6, 6, None),
    "Cascade": SongMeta("YARN Pack 3", "yarn", 6, None, None, None, None, None, None, None, None, None),
    "Don't Touch My Plushies": SongMeta("YARN Pack 3", "yarn", 3, 3, 3, None, None, None, 3, None, None, None),
    "Guardian Angel": SongMeta("YARN Pack 3", "yarn", 5, None, None, None, None, None, None, None, None, None),
    "Kimi no Taion (feat. Eleanor Forte)": SongMeta("YARN Pack 3", "yarn", 3, 3, 2, None, None, None, 4, None, None, None),
    "n u l l s t a r _": SongMeta("YARN Pack 3", "yarn", 5, 0, None, None, 3, 5, None, None, None, None),
    "phleps": SongMeta("YARN Pack 3", "yarn", 2, 1, 0, None, 0, 1, 1, None, None, None),
    "Retry Now (feat. Hatsune Miku)": SongMeta("YARN Pack 3", "yarn", 5, None, None, None, None, None, 6, None, None, None),
    "Year of the Toad (YOTT)": SongMeta("YARN Pack 3", "yarn", 3, 2, 5, None, None, None, 3, 3, 3, None),
    "Deep Geyser Tunez": SongMeta("The Water Cycle", "yarn", None, 6, 6, 6, 3, 3, None, None, None, 5),
    "Hurricane": SongMeta("The Water Cycle", "yarn", 5, 4, 3, None, 3, 4, None, None, None, 4),
    "Liquidic Breakdown": SongMeta("The Water Cycle", "yarn", 3, 4, 5, None, 5, 4, None, None, None, None),
    "Rain": SongMeta("The Water Cycle", "yarn", None, 4, None, None, 4, 5, None, None, None, None),
    "Surface Wind": SongMeta("The Water Cycle", "yarn", 3, 3, 3, 3, 5, 4, 0, None, None, None),
    "Thunderstorm": SongMeta("The Water Cycle", "yarn", 1, 2, 3, None, 1, 1, None, None, None, None),
    "Tsunami": SongMeta("The Water Cycle", "yarn", 3, 3, 6, None, 5, 5, None, None, None, None),
    "Twilight Ocean": SongMeta("The Water Cycle", "yarn", 3, 3, 3, None, 5, 4, None, None, None, None),
    "Water's Under": SongMeta("The Water Cycle", "yarn", None, 3, 4, None, 4, 4, None, None, None, None),
    "Born of Dirt": SongMeta("Assorted Metal 2", "yargdlc", 4, 2, 6, None, None, None, 0, None, None, 4),
    "Deceptive Consequences": SongMeta("Assorted Metal 2", "yargdlc", 4, 3, 6, None, None, None, None, None, None, 4),
    "Event Horizon": SongMeta("Assorted Metal 2", "yargdlc", 3, 4, 4, None, 1, 1, 0, 0, 0, 4),
    "Funeral Waltz": SongMeta("Assorted Metal 2", "yargdlc", 1, 1, 1, None, 2, 2, 1, 1, 1, 1),
    "I.E.D. Vanflip": SongMeta("Assorted Metal 2", "yargdlc", 4, 4, 7, 7, None, None, 0, 0, 0, 0),
    "Introspective Nightmares": SongMeta("Assorted Metal 2", "yargdlc", 6, 6, 7, None, 0, 0, 0, 0, 0, 6),
    "Mr. Jackalope (And His Restless Haunting) / When Days End": SongMeta("Assorted Metal 2", "yargdlc", 6, 2, 4, None, None, None, None, None, None, 4),
    "The Lonesome Tongues": SongMeta("Assorted Metal 2", "yargdlc", 4, 3, 5, None, 0, 1, 0, 0, 0, 3),
    "Train Wreck": SongMeta("Assorted Metal 2", "yargdlc", 2, 1, 7, None, None, None, 0, 0, None, 2),
    "Angels We Have Heard on High": SongMeta("Christmas Keys 2", "yargdlc", None, 2, None, None, 3, 3, None, None, None, None),
    "O Come, All Ye Faithful": SongMeta("Christmas Keys 2", "yargdlc", None, 1, None, None, 2, 2, None, None, None, None),
    "Shchedryk": SongMeta("Christmas Keys 2", "yargdlc", None, 3, None, None, 3, 3, None, None, None, None),
    "Silent Night": SongMeta("Christmas Keys 2", "yargdlc", None, 0, None, None, 1, 1, None, None, None, None),
    "The First Noël": SongMeta("Christmas Keys 2", "yargdlc", None, 2, None, None, 2, 2, None, None, None, None),
    "The Twelve Days of Christmas": SongMeta("Christmas Keys 2", "yargdlc", None, 2, None, None, 2, 2, None, None, None, None),
    "Atelophobia": SongMeta("Teto Pack", "yarn", 2, 2, 3, None, 1, 1, 3, 3, None, 2),
    "Classic J Dies and Goes to Hell Part 1 (feat. Kasane Teto)": SongMeta("Teto Pack", "yarn", 2, 3, 3, None, 3, 4, 3, 3, 3, 2),
    "Fever Dream": SongMeta("Teto Pack", "yarn", 3, 2, 2, None, 3, 4, 4, 4, 4, None),
    "Overload": SongMeta("Teto Pack", "yarn", 2, 4, 1, None, 2, 2, 3, 3, 3, 2),
    "POTETO CHIP": SongMeta("Teto Pack", "yarn", 1, 2, 2, None, 3, 3, 3, 3, 3, None),
    "Ragebait": SongMeta("Teto Pack", "yarn", 3, 3, 4, None, 0, 0, 3, 3, 3, None),
    "REGRET ROCK": SongMeta("Teto Pack", "yarn", 2, 2, 2, None, 2, 2, 2, 2, 2, None),
    "TAZTY!": SongMeta("Teto Pack", "yarn", 2, 2, 4, None, 4, 4, 3, 3, 3, None),
}

#Example on using the Songs Dictionary
#
#for name, data in Songs.items():
#    print("Song Name: " + name)
#    print("5 Fret Guitar Diff: " + str(data.guitar5F))
#    print("5 Fret Bass Diff: " + str(data.bass5F))
#
#If you want to use the Songs Dict in other file add to top of file
#
#from .songinfo import Songs
    
    