[Song]
;
name = 2112 Pt. 6 - Soliloquy
artist = Rush
album = 2112
genre = Prog Rock
year = 1976
song_length = 140399
diff_band = 2
diff_guitar = 2
diff_bass = 1
diff_drums = 1
diff_keys = -1
diff_guitarghl = -1
diff_bassghl = -1
preview_start_time = -1
frets = <color=orange>Neversoft</color>
charter=<color=orange>Neversoft</color>
icon = ghwor
playlist_track = 86
loading_phrase = This song was recorded live for the first time in it's entirety for the Test For Echo tour and released on the 3-CD set Different Stages in 1998.
