[Song]
;
name = Motivation
artist = Sum 41
album = All Killer No Filler
genre = Pop Punk
year = 2001
song_length = 175199
diff_band = 2
diff_guitar = 2
diff_bass = 2
diff_drums = 3
diff_keys = -1
diff_guitarghl = -1
diff_bassghl = -1
preview_start_time = -1
frets = <color=orange>Neversoft</color>
charter=<color=orange>Neversoft</color>
icon = ghwor
album_track = 16000
playlist_track = 50
delay = 0
loading_phrase = This song is about having a lack of motivation. Deryck Whibley said in an interview that this song is like your Sunday, when you can't be bothered doing anything.
