[Song]
;
name = I'm Broken
artist = Pantera
album = Far Beyond Driven
genre = Metal
year = 1994
song_length = 265066
diff_band = 2
diff_guitar = 3
diff_bass = 2
diff_drums = 2
diff_keys = -1
diff_guitarghl = -1
diff_bassghl = -1
preview_start_time = -1
frets = <color=orange>Neversoft</color>
charter=<color=orange>Neversoft</color>
icon = ghwor
album_track = 16000
playlist_track = 35
delay = 0
loading_phrase = The album liner note reads: "This is a Black Sabbath song off of the Paranoid album. So don't freak out on us. We did the song because we wanted to. It has nothing to do with the integrity of our direction. It's a tripped out song. We think you'll dig it. If you don't, don't fucking listen to it. Thanks. On behalf of the rest of Pantera, Phil Anselmo '94."
