[Song]
;
name = Feels Like the First Time
artist = Foreigner
album = Foreigner
genre = Classic Rock
year = 2007
song_length = 253733
diff_band = 2
diff_guitar = 2
diff_bass = 2
diff_drums = 1
diff_keys = -1
diff_guitarghl = -1
diff_bassghl = -1
preview_start_time = -1
frets = <color=orange>Neversoft</color>
charter=<color=orange>Neversoft</color>
icon = ghwor
album_track = 16000
playlist_track = 24
delay = 0
loading_phrase = This was the first song penned by Mick Jones that he ever heard played on the radio. He described his feelings to Lords of Metal on hearing it for the first time: "I was driving to Long Island to go to the sea when this song came on. I was on the bridge and in my mirror you could see the big city. On the radio they said, there is a new band and they have a great song which we will play now and that was my song. I turned the car window down and I started to drive very fast. I will never forget that moment!"
