[Song]
;
name = Interstate Love Song
artist = Stone Temple Pilots
album = Purple
genre = Alternative
year = 1994
song_length = 201399
diff_band = 2
diff_guitar = 2
diff_bass = 2
diff_drums = 1
diff_keys = -1
diff_guitarghl = -1
diff_bassghl = -1
preview_start_time = -1
frets = <color=orange>Neversoft</color>
charter=<color=orange>Neversoft</color>
icon = ghwor
album_track = 16000
playlist_track = 39
delay = 0
loading_phrase = Stone Temple Pilots were voted both Best New Band (by readers) and Worst New Band (by critics) in Rolling Stone's 1994 music awards.
