[Song]
;
name = We're Not Gonna Take It
artist = Twisted Sister
album = Stay Hungry
genre = Heavy Metal
year = 1984
song_length = 270866
diff_band = 2
diff_guitar = 1
diff_bass = 2
diff_drums = 3
diff_keys = -1
diff_guitarghl = -1
diff_bassghl = -1
preview_start_time = -1
frets = <color=orange>Neversoft</color>
charter=<color=orange>Neversoft</color>
icon = ghwor
album_track = 16000
playlist_track = 91
delay = 0
loading_phrase = This was the song that catapulted Twisted Sister to fame. They promoted this single with an innovative video with cartoonish violence featuring a young kid that turns into frontman Dee Snider, telling his father he's "Not gonna take it!"
