[Song]
;
name = I Know What I Am
artist = Band of Skulls
album = Baby Darling Doll Face Honey
genre = Indie Rock
year = 2009
song_length = 203333
count = 1
diff_band = 1
diff_guitar = 1
diff_bass = 0
diff_drums = 1
diff_keys = -1
diff_guitarghl = -1
diff_bassghl = -1
preview_start_time = -1
frets = <color=orange>Neversoft</color>
charter=<color=orange>Neversoft</color>
icon = ghwor
playlist_track = 34
loading_phrase = The trio found themselves playing regularly at the Talking Heads club in Southampton, where a sign of Hamlet holding a skull inspired their name.
