[Song]
;
name = Ravenous
artist = Atreyu
album = Congregation of the Damned
genre = Metal
year = 2009
song_length = 201733
count = 1
diff_band = 3
diff_guitar = 5
diff_bass = 3
diff_drums = 4
diff_keys = -1
diff_guitarghl = -1
diff_bassghl = -1
preview_start_time = -1
frets = <color=orange>Neversoft</color>
charter=<color=orange>Neversoft</color>
icon = ghwor
playlist_track = 59
loading_phrase = Originally named Retribution, they changed their name to "Atreyu" (after the character of the same name from the fantasy book/movie The Neverending Story), when they found out that another band from Hemet, California had already been using Retribution.
