[Song]
;
name = 2112 Pt. 3 - Discovery
artist = Rush
album = 2112
genre = Prog Rock
year = 1976
song_length = 216133
diff_band = 1
diff_guitar = 2
diff_bass = 0
diff_drums = 0
diff_keys = -1
diff_guitarghl = -1
diff_bassghl = -1
preview_start_time = -1
frets = <color=orange>Neversoft</color>
charter=<color=orange>Neversoft</color>
icon = ghwor
album_track = 16000
playlist_track = 83
delay = 0
loading_phrase = This song is actually a criticism of the music industry, and how they try to control song length and style.
