[Song]
;
name = Theme from Spiderman
artist = The Ramones
album = Adios Amigos!
genre = Punk
year = 1995
song_length = 127733
count = 2
diff_band = 2
diff_guitar = 1
diff_bass = 2
diff_drums = 3
diff_keys = -1
diff_guitarghl = -1
diff_bassghl = -1
preview_start_time = -1
frets = <color=orange>Neversoft</color>
charter=<color=orange>Neversoft</color>
icon = ghwor
playlist_track = 75
loading_phrase = The Ramones are often cited as the first punk rock group. Despite achieving only limited commercial success, the band was a major influence on the punk rock movement in both the United States and the United Kingdom.
